services:
  order-service:
    build: .
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/order

    networks:
      - app-network
    depends_on:
      - mongodb
    container_name: order-service


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:
    external: false

networks:
  app-network:
    external: true

